(() => {
  'use strict';
  const c=document.querySelector('#game'),x=c.getContext('2d'),$=q=>document.querySelector(q);
  const u={stage:$('#stage-label'),name:$('#stage-name'),count:$('#crystal-count'),phase:$('#phase'),label:$('#phase-label'),time:$('#phase-time'),fill:$('#phase-fill'),hint:$('#instruction'),start:$('#start-screen'),end:$('#result-screen'),startBtn:$('#start-button'),restart:$('#restart-button'),retry:$('#retry-button')};
  const R=15,DELAY=4,SAMPLE=1/40,MAX=75;
  const levels=[
    {type:'bridge',name:'과거의 다리',hint:'보라색 과거가 릴레이를 밟으면, 청록색 다리가 생깁니다.',start:[.15,.55],sw:[.29,.55],door:[.84,.55],bridge:[.55,.39,.1,.32],walls:[]},
    {type:'sync',name:'엇갈린 약속',hint:'보라는 보라색 패드에, 청록은 청록색 패드에 동시에 서야 합니다.',start:[.15,.72],sw:[.3,.35],now:[.7,.7],door:[.87,.7],walls:[[.46,.2,.07,.5],[.46,.8,.07,.05]]},
    {type:'bridge',name:'두 개의 강',hint:'과거가 릴레이를 밟는 짧은 순간에 다리를 건너세요.',start:[.14,.3],sw:[.28,.7],door:[.86,.35],bridge:[.57,.2,.09,.55],walls:[[.39,.48,.15,.06],[.7,.52,.07,.32]]},
    {type:'portal',name:'시간 포털',hint:'현재의 내가 포털에 들어가면, 4초 뒤 과거도 반대편에 나타납니다.',start:[.14,.72],sw:[.7,.3],door:[.87,.7],portalA:[.31,.6],portalB:[.67,.3],walls:[[.44,.2,.07,.45],[.44,.76,.07,.08]]},
    {type:'sync',name:'두 시대의 문',hint:'과거와 현재가 각자의 패드에 동시에 서도록 4초를 설계하세요.',start:[.14,.3],sw:[.32,.69],now:[.7,.3],door:[.87,.3],walls:[[.45,.18,.07,.27],[.45,.64,.07,.18],[.62,.45,.07,.42]]}
  ];
  let W=innerWidth,H=innerHeight,dpr=1,state='intro',stage=0,present,past,history=[],last=0,clock=0,stars=[],particles=[],portalCooldown=0;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=(a,b)=>a+Math.random()*(b-a);
  function area(){return{l:24,r:W-24,t:145,b:H-95,w:W-48,h:H-240}}function pt(n){const a=area();return{x:a.l+n[0]*a.w,y:a.t+n[1]*a.h}}function rr(n){const a=area();return{x:a.l+n[0]*a.w,y:a.t+n[1]*a.h,w:n[2]*a.w,h:n[3]*a.h}}
  function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.floor(W*H/9000)},()=>({x:Math.random()*W,y:Math.random()*H,a:rnd(.15,.7),r:rnd(.3,1.2)}));if(state!=='intro')setup()}
  function setup(){const l=levels[stage],s=pt(l.start);present={x:s.x,y:s.y,tx:s.x,ty:s.y};past=null;history=[];clock=0;particles=[];portalCooldown=0;state='play';u.stage.textContent=`STAGE ${String(stage+1).padStart(2,'0')}`;u.name.textContent=l.name;u.count.textContent='DEVICE OFF';u.hint.textContent=l.hint;u.label.textContent='PAST SELF IS';u.time.textContent='4.0s BEHIND';u.fill.style.width='100%';u.phase.classList.add('replay');u.retry.textContent='↻ 다시 시도';u.retry.hidden=true}
  function begin(){stage=0;u.start.classList.remove('show');u.end.classList.remove('show');setup();last=performance.now();requestAnimationFrame(frame)}
  function open(){const l=levels[stage],sw=pt(l.sw);return !!(past&&dist(past,sw)<48&&(l.type!=='sync'||dist(present,pt(l.now))<43))}
  function hitWall(px,py){const a=area();if(px<a.l+R||px>a.r-R||py<a.t+R||py>a.b-R)return true;for(const n of levels[stage].walls){const q=rr(n),nx=clamp(px,q.x,q.x+q.w),ny=clamp(py,q.y,q.y+q.h);if(Math.hypot(px-nx,py-ny)<R)return true}const l=levels[stage];if(l.bridge&&!open()){const q=rr(l.bridge),nx=clamp(px,q.x,q.x+q.w),ny=clamp(py,q.y,q.y+q.h);if(Math.hypot(px-nx,py-ny)<R)return true}return false}
  function update(dt){if(state==='play'){clock+=dt;portalCooldown-=dt;const dx=present.tx-present.x,dy=present.ty-present.y,l=Math.hypot(dx,dy)||1,m=Math.min(l,255*dt),nx=present.x+dx/l*m,ny=present.y+dy/l*m;if(!hitWall(nx,ny)){present.x=nx;present.y=ny}const level=levels[stage];if(level.portalA&&portalCooldown<0&&dist(present,pt(level.portalA))<27){const out=pt(level.portalB);present.x=present.tx=out.x;present.y=present.ty=out.y;portalCooldown=.7;burst(out.x,out.y,'#ffd166',32)}history.push({x:present.x,y:present.y});if(history.length>DELAY/SAMPLE){past=history[history.length-1-Math.floor(DELAY/SAMPLE)]}const door=pt(level.door),isOpen=open();if(isOpen){u.count.textContent=level.type==='sync'?'SYNCHRONIZED':'RELAY ON';u.count.style.color='#61f5e6';u.hint.textContent=level.type==='sync'?'두 시대가 연결됐습니다 — 청록 EXIT에 들어가세요!':'릴레이가 켜졌습니다 — 오른쪽 EXIT로 이동하세요!'}else{u.count.textContent='DEVICE OFF';u.count.style.color='';}if(isOpen&&dist(present,door)<72){success();return}if(clock>MAX){clock=0;history=[];past=null;u.hint.textContent='시간 연결이 끊겼어요. 다시 시도하세요.';u.retry.hidden=false}u.time.textContent=past?'4.0s BEHIND':`${Math.max(0,DELAY-clock).toFixed(1)}s TO ECHO`;u.fill.style.width=`${Math.min(1,clock/DELAY)*100}%`}
    particles=particles.filter(q=>(q.life-=dt)>0);for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.95;q.vy*=.95}}
  function success(){state='clear';wonAt=performance.now();burst(present.x,present.y,'#61f5e6',72);u.count.textContent='ROOM CLEAR';u.label.textContent='SYNCHRONIZED';u.time.textContent='✓';u.hint.textContent=`${levels[stage].name} 완료 — 다음 장치로 넘어가세요.`;u.retry.textContent=stage===levels.length-1?'결과 보기 →':'다음 방 →';u.retry.hidden=false}
  function nextStage(){stage++;if(stage===levels.length){state='finished';u.end.classList.add('show')}else setup()}
  function burst(X,Y,color,n){for(let i=0;i<n;i++){const a=Math.random()*7,s=rnd(25,210);particles.push({x:X,y:Y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.25,.9),r:rnd(1,4),color})}}
  function draw(){x.clearRect(0,0,W,H);const g=x.createRadialGradient(present?.x||W/2,present?.y||H/2,0,W/2,H/2,Math.max(W,H)*.8);g.addColorStop(0,'#15173a');g.addColorStop(1,'#070713');x.fillStyle=g;x.fillRect(0,0,W,H);for(const s of stars){x.globalAlpha=s.a;x.fillStyle='#c4d0ff';x.fillRect(s.x,s.y,s.r,s.r)}x.globalAlpha=1;const a=area();x.strokeStyle='rgba(126,119,200,.15)';x.strokeRect(a.l,a.t,a.w,a.h);if(!levels[stage])return;const l=levels[stage],on=open();for(const n of l.walls)wall(rr(n));if(l.bridge)bridge(rr(l.bridge),on);if(l.portalA){portal(pt(l.portalA),'IN');portal(pt(l.portalB),'OUT')}plate(pt(l.sw),on);if(l.now)nowPad(pt(l.now),on);exit(pt(l.door),on);if(history.length>2)trail();if(past)orb(past,'#ed71ff','4S AGO');if(present)orb(present,'#61f5e6','NOW');for(const q of particles){x.globalAlpha=Math.max(0,q.life/.9);x.fillStyle=q.color;x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.fill()}x.globalAlpha=1}
  function wall(q){x.fillStyle='rgba(65,58,98,.75)';x.fillRect(q.x,q.y,q.w,q.h);x.strokeStyle='rgba(169,151,255,.5)';x.strokeRect(q.x,q.y,q.w,q.h)}
  function bridge(q,on){x.fillStyle=on?'rgba(97,245,230,.45)':'rgba(255,255,255,.05)';x.fillRect(q.x,q.y,q.w,q.h);x.strokeStyle=on?'#61f5e6':'#574f6b';x.setLineDash([5,5]);x.strokeRect(q.x,q.y,q.w,q.h);x.setLineDash([]);x.fillStyle=on?'#dffffa':'#928aa2';x.font='9px DM Mono';x.textAlign='center';x.fillText(on?'PAST BRIDGE':'RELAY BRIDGE',q.x+q.w/2,q.y+q.h/2)}
  function plate(p,on){x.save();x.translate(p.x,p.y);x.strokeStyle=on?'#61f5e6':'#ed71ff';x.shadowBlur=on?25:12;x.shadowColor=x.strokeStyle;x.lineWidth=3;x.beginPath();x.arc(0,0,32,0,7);x.stroke();x.fillStyle='rgba(237,113,255,.15)';x.fill();x.fillStyle=x.strokeStyle;x.font='10px DM Mono';x.textAlign='center';x.fillText('PAST ONLY',0,4);x.restore()}
  function nowPad(p,on){x.save();x.translate(p.x,p.y);x.strokeStyle=on?'#61f5e6':'#61b8d8';x.shadowBlur=on?25:10;x.shadowColor=x.strokeStyle;x.lineWidth=3;x.beginPath();x.rect(-28,-28,56,56);x.stroke();x.fillStyle='rgba(97,245,230,.12)';x.fill();x.fillStyle=x.strokeStyle;x.font='9px DM Mono';x.textAlign='center';x.fillText('NOW ONLY',0,4);x.restore()}
  function portal(p,label){x.save();x.translate(p.x,p.y);x.strokeStyle='#ffd166';x.shadowBlur=18;x.shadowColor='#ffd166';x.lineWidth=3;x.beginPath();x.arc(0,0,23,0,7);x.stroke();x.fillStyle='#ffd166';x.font='9px DM Mono';x.textAlign='center';x.fillText(label,0,4);x.restore()}
  function exit(p,on){x.save();x.translate(p.x,p.y);x.shadowBlur=on?32:0;x.shadowColor='#ffd166';x.fillStyle=on?'rgba(255,209,102,.2)':'rgba(81,73,96,.2)';x.beginPath();x.arc(0,0,62,0,7);x.fill();x.strokeStyle=on?'#ffd166':'#514960';x.lineWidth=4;x.setLineDash(on?[8,5]:[3,7]);x.beginPath();x.arc(0,0,54,0,7);x.stroke();x.setLineDash([]);x.fillStyle=on?'#fff2be':'#8f8ba0';x.font='700 13px DM Mono';x.textAlign='center';x.fillText(on?'EXIT →':'LOCKED',0,4);x.restore()}
  function trail(){x.save();x.globalAlpha=.13;x.strokeStyle='#ed71ff';x.lineWidth=2;x.beginPath();history.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();x.restore()}
  function orb(p,color,label){x.save();x.shadowBlur=25;x.shadowColor=color;x.fillStyle=color;x.globalAlpha=.2;x.beginPath();x.arc(p.x,p.y,R+5,0,7);x.fill();x.globalAlpha=1;x.beginPath();x.arc(p.x,p.y,R,0,7);x.fill();x.fillStyle='#ecffff';x.beginPath();x.arc(p.x-4,p.y-4,5,0,7);x.fill();x.fillStyle=color;x.font='9px DM Mono';x.textAlign='center';x.fillText(label,p.x,p.y-R-13);x.restore()}
  function frame(t){if(state==='intro'||state==='finished')return;const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}
  function pointer(e){if(state!=='play')return;const r=c.getBoundingClientRect();present.tx=e.clientX-r.left;present.ty=e.clientY-r.top}c.addEventListener('pointermove',pointer);c.addEventListener('pointerdown',pointer);u.startBtn.addEventListener('click',begin);u.restart.addEventListener('click',begin);u.retry.addEventListener('click',()=>state==='clear'?nextStage():setup());addEventListener('resize',resize);resize();draw();
})();
